spring:
  application:
    name: customer-service
  # config database
  datasource:
    driver-class-name: org.postgresql.Driver  # Ensure the driver class is specified
    url: jdbc:postgresql://localhost:5432/openfeign_db
    username: postgres
    password: 20033

  # config data jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # This fixes your hibernate formatting issue
server:
  port: 8081